import Link from "next/link";
import { notFound } from "next/navigation";
import { quoteDecisionAction } from "@/app/actions";
import { Flash } from "@/components/flash";
import { StatusBadge } from "@/components/status-badge";
import { formatDate, money } from "@/lib/format";
import { getQuoteAccess } from "@/lib/services";
export const dynamic="force-dynamic";
export default async function QuotePage({params,searchParams}:{params:Promise<{token:string}>;searchParams:Promise<{success?:string;error?:string;submitted?:string}>}){const {token}=await params;const query=await searchParams;const q=getQuoteAccess(token);if(!q)notFound();const style={"--company-primary":q.primary_color,"--company-accent":q.accent_color} as React.CSSProperties;return <main className="tracking-shell" style={style}><div className="tracking-head" style={{background:`linear-gradient(135deg,${q.primary_color},#102c32)`}}><div className="eyebrow" style={{color:"#d8eeee"}}>{q.company_name}</div><h1>Shipment request</h1><p style={{margin:0}}>{q.sender_name} → {q.receiver_name}</p></div><div className="mt"><Flash success={query.submitted?"Request submitted. The company will review it and issue a preliminary quote here.":query.success} error={query.error}/></div><section className="card mt"><div className="card-head"><h3>{q.contents}</h3><StatusBadge value={q.state}/></div><div className="card-body"><div className="kpi-row"><span>Package</span><b>{q.description}</b></div><div className="kpi-row"><span>Service</span><b>{q.origin_mode} → {q.destination_mode}</b></div>{q.amount!=null?<><div className="kpi-row"><span>Preliminary quote</span><b>{money(q.amount,q.currency)}</b></div><div className="kpi-row"><span>Quote expires</span><b>{formatDate(q.expires_at)}</b></div>{q.expected_delivery_date&&<div className="kpi-row"><span>Expected delivery</span><b>{formatDate(q.expected_delivery_date)}</b></div>}<div className="notice alert mt">{q.notes||"The final amount may change after physical inspection."}</div>{q.state==="PRELIMINARY_QUOTE_ISSUED"&&<div className="actions mt"><form action={quoteDecisionAction}><input type="hidden" name="token" value={token}/><input type="hidden" name="decision" value="ACCEPT"/><button className="btn" style={{background:q.primary_color}}>Accept preliminary quote</button></form><form action={quoteDecisionAction}><input type="hidden" name="token" value={token}/><input type="hidden" name="decision" value="ABANDON"/><button className="btn secondary">Abandon request</button></form></div>}{q.state==="CUSTOMER_ACCEPTED"&&<div className="notice success mt">You accepted the quote. The company can now confirm and activate the shipment.</div>}{q.state==="COMPANY_CONFIRMED"&&<div className="notice success mt">The shipment has been confirmed. Use the tracking link sent by the company.</div>}</>:<div className="notice mt">A preliminary quote has not been issued yet. You can return to this private link later.</div>}</div></section><div className="mt"><Link className="link" href={`/c/${q.company_handle}`}>Return to {q.company_name}</Link></div></main>}
