import { redirect } from "next/navigation";
import { createTeamMemberAction } from "@/app/actions";
import { Flash } from "@/components/flash";
import { PageTitle } from "@/components/page-title";
import { StatusBadge } from "@/components/status-badge";
import { requireMember } from "@/lib/auth";
import { getWorkspaceSnapshot } from "@/lib/services";
export const dynamic="force-dynamic";
export default async function TeamPage({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){const ctx=await requireMember();if(!["OWNER", "ADMIN"].includes(ctx.role))redirect("/app");const s=getWorkspaceSnapshot(ctx);const flash=await searchParams;const canManage=["OWNER","ADMIN"].includes(ctx.role);return <><Flash {...flash}/><PageTitle eyebrow="People and scope" title="Team members" description="MaliktBoard does not create a Driver role. Operational access comes from role plus assigned locations."/><div className="grid two-col"><section className="card"><div className="table-wrap"><table className="table"><thead><tr><th>Name</th><th>Role</th><th>Locations</th><th>Status</th></tr></thead><tbody>{s.members.map((m:any)=><tr key={m.id}><td><b>{m.name}</b><div className="muted small">{m.email||m.phone}</div></td><td><StatusBadge value={m.role}/></td><td>{m.locations||"No location assignment"}</td><td><StatusBadge value={m.active?"ACTIVE":"SUSPENDED"}/></td></tr>)}</tbody></table></div></section><section className="card"><div className="card-head"><h3>Add team member</h3></div>{canManage?<form className="card-body form-grid" action={createTeamMemberAction}><div className="field"><label>Name</label><input className="input" name="name" required/></div><div className="field"><label>Email</label><input className="input" name="email" type="email" required/></div><div className="field"><label>Phone</label><input className="input" name="phone"/></div><div className="field"><label>Temporary password</label><input className="input" name="password" type="password" minLength={10} required/></div><div className="field full"><label>Role</label><select className="select" name="role"><option>TEAM_MEMBER</option><option>SUPERVISOR</option><option>ADMIN</option><option>VIEWER</option></select></div><div className="field full"><label>Assigned locations</label><div className="checkbox-grid">{s.locations.map((l:any)=><label className="check" key={l.id}><input type="checkbox" name="locationIds" value={l.id}/>{l.name}</label>)}</div></div><button className="btn full">Create team account</button></form>:<div className="card-body notice">Only Owners and Administrators can create team accounts.</div>}</section></div></>}
