import type { TeamRole } from "./types";

export type Permission =
  | "COMPANY_MANAGE"
  | "TEAM_MANAGE"
  | "NETWORK_MANAGE"
  | "REQUEST_REVIEW"
  | "QUOTE_ISSUE"
  | "SHIPMENT_ACTIVATE"
  | "SHIPMENT_UPDATE"
  | "BATCH_CREATE"
  | "BATCH_UPDATE"
  | "SUPERVISOR_OVERRIDE"
  | "EVIDENCE_VIEW_SENSITIVE"
  | "PAYMENT_MANAGE"
  | "READ_ONLY";

const rolePermissions: Record<TeamRole, Set<Permission>> = {
  OWNER: new Set(["COMPANY_MANAGE","TEAM_MANAGE","NETWORK_MANAGE","REQUEST_REVIEW","QUOTE_ISSUE","SHIPMENT_ACTIVATE","SHIPMENT_UPDATE","BATCH_CREATE","BATCH_UPDATE","SUPERVISOR_OVERRIDE","EVIDENCE_VIEW_SENSITIVE","PAYMENT_MANAGE","READ_ONLY"]),
  ADMIN: new Set(["COMPANY_MANAGE","TEAM_MANAGE","NETWORK_MANAGE","REQUEST_REVIEW","QUOTE_ISSUE","SHIPMENT_ACTIVATE","SHIPMENT_UPDATE","BATCH_CREATE","BATCH_UPDATE","SUPERVISOR_OVERRIDE","EVIDENCE_VIEW_SENSITIVE","PAYMENT_MANAGE","READ_ONLY"]),
  SUPERVISOR: new Set(["REQUEST_REVIEW","QUOTE_ISSUE","SHIPMENT_ACTIVATE","SHIPMENT_UPDATE","BATCH_CREATE","BATCH_UPDATE","SUPERVISOR_OVERRIDE","EVIDENCE_VIEW_SENSITIVE","PAYMENT_MANAGE","READ_ONLY"]),
  TEAM_MEMBER: new Set(["SHIPMENT_UPDATE","BATCH_UPDATE","READ_ONLY"]),
  VIEWER: new Set(["READ_ONLY"]),
};

export function hasPermission(role: TeamRole, permission: Permission): boolean {
  return rolePermissions[role].has(permission);
}
