import { redirect } from "next/navigation";
import Link from "next/link";
import { activateShipmentAction, issueQuoteAction } from "@/app/actions";
import { Flash } from "@/components/flash";
import { PageTitle } from "@/components/page-title";
import { StatusBadge } from "@/components/status-badge";
import { requireMember } from "@/lib/auth";
import { formatDate, money } from "@/lib/format";
import { getWorkspaceSnapshot } from "@/lib/services";
export const dynamic="force-dynamic";
export default async function RequestsPage({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){const ctx=await requireMember();if(!["OWNER", "ADMIN", "SUPERVISOR", "VIEWER"].includes(ctx.role))redirect("/app");const s=getWorkspaceSnapshot(ctx);const flash=await searchParams;return <><Flash {...flash}/><PageTitle eyebrow="Intake" title="Shipment requests" description="One request represents one physical package. Issue a preliminary quote, wait for customer acceptance, then activate the shipment."/><div className="stack">{s.requests.map((r:any)=><section className="card" key={r.id}><div className="card-head"><div><b>{r.sender_name} → {r.receiver_name}</b><div className="muted small">{r.contents} · submitted {formatDate(r.submitted_at)}</div></div><StatusBadge value={r.state}/></div><div className="card-body grid equal-two"><div><div className="kpi-row"><span>Sender</span><b>{r.sender_name} · {r.sender_phone}</b></div><div className="kpi-row"><span>Receiver</span><b>{r.receiver_name} · {r.receiver_phone}</b></div><div className="kpi-row"><span>Package</span><b>{r.description}</b></div><div className="kpi-row"><span>Service</span><b>{r.origin_mode} → {r.destination_mode}</b></div>{r.photo_path&&<Link className="link" href={`/api/request-photo/${r.id}`} target="_blank">View package photo</Link>}</div><div>{r.quote_amount!=null?<div className="notice"><b>{money(r.quote_amount,r.quote_currency)}</b><br/>Expires {formatDate(r.quote_expires_at)}<br/>{r.expected_delivery_date&&<>Estimated delivery {formatDate(r.expected_delivery_date)}<br/></>}<span className="muted">Customer link: </span><a className="link" target="_blank" href={`/q/${r.quoteToken}`}>open secure quote page</a></div>:<form action={issueQuoteAction} className="form-grid"><input type="hidden" name="requestId" value={r.id}/><div className="field"><label>Preliminary amount (ETB)</label><input className="input" name="amount" type="number" min="0" required/></div><div className="field"><label>Expected delivery date</label><input className="input" name="expectedDeliveryDate" type="date"/></div><div className="field full"><label>Quote note</label><textarea className="textarea" name="notes" defaultValue="Final amount may change after physical inspection."/></div><button className="btn full">Issue preliminary quote</button></form>}{r.state==="CUSTOMER_ACCEPTED"&&<form action={activateShipmentAction} className="mt"><input type="hidden" name="requestId" value={r.id}/><button className="btn">Confirm and activate shipment</button></form>}{r.state==="PRELIMINARY_QUOTE_ISSUED"&&<div className="notice alert mt">Waiting for the customer to accept through the secure quote link.</div>}</div></div></section>)}{s.requests.length===0&&<div className="card empty">No shipment requests yet.</div>}</div></>}
