import { redirect } from "next/navigation";
import Link from "next/link";
import { updateBrandingAction } from "@/app/actions";
import { Flash } from "@/components/flash";
import { PageTitle } from "@/components/page-title";
import { requireMember } from "@/lib/auth";
import { getWorkspaceSnapshot } from "@/lib/services";
export const dynamic="force-dynamic";
export default async function SettingsPage({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){const ctx=await requireMember();if(!["OWNER", "ADMIN"].includes(ctx.role))redirect("/app");const s=getWorkspaceSnapshot(ctx);const flash=await searchParams;const canManage=["OWNER","ADMIN"].includes(ctx.role);return <><Flash {...flash}/><PageTitle eyebrow="Company identity" title="Branding and public page" description="The company handle, story, colors, and layout create a distinct customer-facing request and tracking experience." action={<Link className="btn secondary" target="_blank" href={`/c/${s.company.handle}`}>Preview public page</Link>}/><section className="card"><div className="card-head"><h3>@{s.company.handle}</h3></div>{canManage?<form className="card-body form-grid" action={updateBrandingAction}><div className="field full"><label>Tagline</label><input className="input" name="tagline" defaultValue={s.company.tagline} required/></div><div className="field full"><label>Company story</label><textarea className="textarea" name="story" defaultValue={s.company.story} required/></div><div className="field"><label>Phone</label><input className="input" name="phone" defaultValue={s.company.phone} required/></div><div className="field"><label>Email</label><input className="input" type="email" name="email" defaultValue={s.company.email||""}/></div><div className="field"><label>Primary color</label><input className="input" type="color" name="primary" defaultValue={s.company.primary_color}/></div><div className="field"><label>Secondary color</label><input className="input" type="color" name="secondary" defaultValue={s.company.secondary_color}/></div><div className="field"><label>Accent color</label><input className="input" type="color" name="accent" defaultValue={s.company.accent_color}/></div><div className="field"><label>Page layout</label><select className="select" name="heroStyle" defaultValue={s.company.hero_style}><option value="split">Split</option><option value="centered">Centered</option><option value="editorial">Editorial</option></select></div><button className="btn full">Save branding</button></form>:<div className="card-body notice">Only Owners and Administrators can change company branding.</div>}</section></>}
