import { redirect } from "next/navigation";
import { Boxes, PackageCheck, Truck, UsersRound } from "lucide-react";
import { PageTitle } from "@/components/page-title";
import { StatCard } from "@/components/stat-card";
import { requireMember } from "@/lib/auth";
import { money } from "@/lib/format";
import { getWorkspaceSnapshot } from "@/lib/services";
export const dynamic="force-dynamic";
export default async function AnalyticsPage(){const ctx=await requireMember();if(!["OWNER", "ADMIN", "SUPERVISOR", "VIEWER"].includes(ctx.role))redirect("/app");const s=getWorkspaceSnapshot(ctx);const delivered=s.shipments.filter((x:any)=>x.state==="DELIVERED");const revenue=s.shipments.reduce((sum:number,x:any)=>sum+(x.payment_status==="PAID"?(x.final_amount??x.preliminary_amount):0),0);return <><PageTitle eyebrow="Operational totals" title="Simple analytics" description="Launch-stage counts derived from real shipment and batch records—not hardcoded business-intelligence charts."/><div className="grid stats"><StatCard label="Shipments" value={s.shipments.length} note="Visible in your company workspace" icon={Boxes}/><StatCard label="In transit" value={s.shipments.filter((x:any)=>x.state==="IN_TRANSIT").length} note="Active Route Leg movement" icon={Truck}/><StatCard label="Delivered" value={delivered.length} note="Completed customer handoffs" icon={PackageCheck}/><StatCard label="Active team" value={s.members.filter((x:any)=>x.active).length} note="Across assigned locations" icon={UsersRound}/></div><section className="card"><div className="card-head"><h3>Financial recording</h3></div><div className="card-body"><div className="kpi-row"><span>Recorded paid shipment value</span><b>{money(revenue,"ETB")}</b></div><div className="kpi-row"><span>Unpaid shipments</span><b>{s.shipments.filter((x:any)=>x.payment_status==="UNPAID").length}</b></div><div className="kpi-row"><span>Partial payments</span><b>{s.shipments.filter((x:any)=>x.payment_status==="PARTIALLY_PAID").length}</b></div></div></section></>}
