import Link from "next/link";
import { createBatchAction } from "@/app/actions";
import { Flash } from "@/components/flash";
import { PageTitle } from "@/components/page-title";
import { StatusBadge } from "@/components/status-badge";
import { requireMember } from "@/lib/auth";
import { formatDate } from "@/lib/format";
import { getWorkspaceSnapshot } from "@/lib/services";
export const dynamic="force-dynamic";
export default async function BatchesPage({searchParams}:{searchParams:Promise<{success?:string;error?:string}>}){const ctx=await requireMember();const s=getWorkspaceSnapshot(ctx);const flash=await searchParams;return <><Flash {...flash}/><PageTitle eyebrow="Grouped movement" title="Dispatch Batches" description="A Dispatch Batch contains many shipments moving together through exactly one Route Leg."/><div className="grid two-col"><section className="card"><div className="card-head"><h3>Existing batches</h3></div><div className="table-wrap"><table className="table"><thead><tr><th>Batch</th><th>Route Leg</th><th>Shipments</th><th>Status</th><th>Expected</th></tr></thead><tbody>{s.batches.map((b:any)=><tr key={b.id}><td><Link className="link" href={`/app/batches/${b.id}`}>{b.batch_number}</Link></td><td>{b.origin_name}<div className="muted small">→ {b.destination_name}</div></td><td>{b.shipment_count}</td><td><StatusBadge value={b.state}/></td><td>{formatDate(b.expected_departure)}</td></tr>)}</tbody></table>{s.batches.length===0&&<div className="empty">No Dispatch Batches yet.</div>}</div></section><section className="card"><div className="card-head"><h3>Create Dispatch Batch</h3></div><form className="card-body form-grid" action={createBatchAction}><div className="field full"><label>Route Leg</label><select className="select" name="routeLegId" required><option value="">Select route</option>{s.routeLegs.filter((x:any)=>x.active).map((leg:any)=><option key={leg.id} value={leg.id}>{leg.code}: {leg.origin_name} → {leg.destination_name}</option>)}</select></div><div className="field"><label>Expected departure</label><input className="input" type="datetime-local" name="expectedDeparture"/></div><div className="field"><label>Expected arrival</label><input className="input" type="datetime-local" name="expectedArrival"/></div><button className="btn full">Create draft batch</button></form></section></div></>}
